#!/usr/bin/env python3
from turtle import *
import math

def saw_wave(x):
    return math.fmod(x, 1.0)

def clamp(a, b, c):
    return min(max(a, b), c)

class Vec2:
    def __init__(self, x, y):
        self.x = float(x)
        self.y = float(y)

    def get_length(self):
        return math.sqrt(self.x * self.x + self.y * self.y)

    def get_angle(self):
        return math.atan(self.y / self.x)

    def get_normalized(self):
        normalized_x = self.x / self.get_length()
        normalized_y = self.y / self.get_length()
        return Vec2(normalized_x, normalized_y)

    @staticmethod
    def from_angle(angle):
        height = sin(angle)
        length = cos(angle)
        return Vec2(length, height)

class Vec3:
    def __init__(self, r, g, b):
        self.r = float(r)
        self.g = float(g)
        self.b = float(b)

# 160, 90 is best compromise between render-speed and quality
# 48, 27 isn't bad
SCREEN_SIZE = Vec2(80, 45)
WINDOW_SIZE = Vec2(1920, 1080)
PI = 3.14159
TAU = 6.28318


pen = Turtle()
delay(0)
colormode(1.0)
tracer(0, 0)
setworldcoordinates(0, SCREEN_SIZE.y, SCREEN_SIZE.x, 0)
pen.screen.title("Imitation Fragment Shader")
pen.shape("square")
pen.shapetransform(WINDOW_SIZE.x / SCREEN_SIZE.x / 5.0, 0.0, 0.0, WINDOW_SIZE.y / SCREEN_SIZE.y / 5.0)

frame = 0
frame_dilation = 4.0

# I believe the colors might not be too accurate, because I don't know if the dot is centered on the pen's location or not.
def frag(frag_coord):
    COLOR = Vec3(0.2, 0.5, 1)
    uv = Vec2(float(frag_coord.x) / SCREEN_SIZE.x, float(frag_coord.y) / SCREEN_SIZE.y)
    
    uv = Vec2(uv.x * 2.0 - 1.0, uv.y * 2.0 - 1.0)
    
    uv.x *= (float(SCREEN_SIZE.x) / float(SCREEN_SIZE.y))
    
    uv.x += math.cos(frame * PI / frame_dilation) * 0.4
    uv.y += math.sin(frame * PI / frame_dilation) * 0.4
    
    inverse_length = 1.0 - min(uv.get_length(), 1.0)
    #inverse_length += 0.2
    inverse_length *= inverse_length
    #inverse_length *= (float(math.sin(frame * PI / frame_dilation)) + 1.0) / 2.0
    
    COLOR = Vec3(
        clamp(COLOR.r * inverse_length, 0.0, 1.0), 
        clamp(COLOR.g * inverse_length, 0.0, 1.0), 
        clamp(COLOR.b * inverse_length, 0.0, 1.0),
    )
    
    return COLOR

def draw():
    for y_pixel in range(1, int(SCREEN_SIZE.y), 1):
        for x_pixel in range(1, int(SCREEN_SIZE.x), 1):
            frag_coord = Vec2(x_pixel, y_pixel)
            COLOR = frag(frag_coord)
            pen.teleport(frag_coord.x, frag_coord.y)
            pen.color(COLOR.r, COLOR.g, COLOR.b)
            pen.stamp()

while True:
    pen.clearstamps()
    draw()
    update()
    frame += 1
