#!/usr/bin/env python3
from turtle import *
import math

# https://iquilezles.org/articles/sdfrepetition/
# https://michaelwalczyk.com/blog-ray-marching.html

class Vec2:
    def __init__(self, x, y):
        self.x = float(x)
        self.y = float(y)

    def get_length(self):
        return math.sqrt(self.x * self.x + self.y * self.y)
    
    def get_normalized(self):
        normalized_x = self.x / self.get_length()
        normalized_y = self.y / self.get_length()
        return Vec2(normalized_x, normalized_y)
    
    def subtract(self, b):
        return Vec2(
            self.x - b.x,
            self.y - b.y,
        )

    def subtract_scalar(self, scalar):
        return Vec2(
            self.x - float(scalar),
            self.y - float(scalar),
        )
    
    def add(self, b):
        return Vec2(
            self.x + b.x,
            self.y + b.y,
        )
    
    def add_scalar(self, scalar):
        return Vec2(
            self.x + float(scalar),
            self.y + float(scalar),
        )
    
    def divide(self, b):
        return Vec2(
            self.x / b.x,
            self.y / b.y,
        )

    def divide_scalar(self, scalar):
        return Vec2(
            self.x / scalar,
            self.y / scalar,
        )

    def multiply(self, b):
        return Vec2(
            self.x * b.x,
            self.y * b.y,
        )

    def multiply_scalar(self, scalar):
        return Vec2(
            self.x * scalar,
            self.y * scalar,
        )
    
    def abs(self): 
        return Vec2(
            float(abs(self.x)),
            float(abs(self.y)),
        )
    
    @staticmethod
    def max(a, b):
        return Vec2(
            max(a.x, b.x),
            max(a.y, b.y),
        )
    
    @staticmethod
    def min(a, b):
        return Vec2(
            min(a.x, b.y),
            min(a.x, b.y),
        )

class Vec3:
    # I wish I had pointers for x, y, and z
    def __init__(self, r, g, b):
        self.r = float(r)
        self.g = float(g)
        self.b = float(b)
    
    def subtract(self, b):
        return Vec3(
            self.r - b.r,
            self.g - b.g,
            self.b - b.b,
        )
    
    def subtract_scalar(self, scalar):
        return Vec3(
            self.r - float(scalar),
            self.g - float(scalar),
            self.b - float(scalar),
        )
    
    def add(self, b):
        return Vec3(
            self.r + b.r,
            self.g + b.g,
            self.b + b.b,
        )
    
    def add_scalar(self, scalar):
        return Vec3(
            self.r + float(scalar),
            self.g + float(scalar),
            self.b + float(scalar),
        )

    def divide(self, b):
        return Vec3(
            self.r / b.r,
            self.g / b.g,
            self.b / b.b,
        )
    
    def divide_scalar(self, scalar):
        return Vec3(
            self.r / float(scalar),
            self.g / float(scalar),
            self.b / float(scalar),
        )

    def multiply(self, b):
        return Vec3(
            self.r * b.r,
            self.g * b.g,
            self.b * b.b,
        )
    
    def multiply_scalar(self, scalar):
        return Vec3(
            self.r * float(scalar),
            self.g * float(scalar),
            self.b * float(scalar),
        )
    
    def get_length(self):
        return float(math.sqrt(self.r * self.r + self.g * self.g + self.b * self.b))
    
    def get_normalized(self):
        return Vec3(
            self.r / float(self.get_length()),
            self.g / float(self.get_length()),
            self.b / float(self.get_length()),
        )
    
    def abs(self):
        return Vec3(
            float(abs(self.r)),
            float(abs(self.g)),
            float(abs(self.b)),
        )
    
    def floor(self):
        return Vec3(
            float(math.floor(self.r)),
            float(math.floor(self.g)),
            float(math.floor(self.b)),
        )
    
    @staticmethod
    def max(a, b):
        return Vec3(
            max(a.r, b.r),
            max(a.g, b.g),
            max(a.b, b.b),
        )
    
    @staticmethod
    def min(a, b):
        return Vec3(
            min(a.r, b.r),
            min(a.g, b.g),
            min(a.b, b.b),
        )

# 160, 90 is best compromise between render-speed and quality
# 48, 27 isn't bad
SCREEN_SIZE = Vec2(240, 135)
WINDOW_SIZE = Vec2(1920, 1080)
ZOOM = 0.4
FRAGMENT_SIZE_MODIFIER = 0.0475
PI = 3.14159
TAU = 6.28318
MARCHES = 80
MAX_RENDER_DISTANCE = 200.0
MIN_RENDER_DISTANCE = 0.015625
PILLAR_SIZE = Vec3(1.0, 13.0, 1.0)

run_simulation = True

pen = Turtle()
delay(0)
colormode(1.0)
tracer(0, 0)
setworldcoordinates(0, SCREEN_SIZE.y, SCREEN_SIZE.x, 0)
pen.screen.title("Imitation Fragment Shader")
pen.shape("square")
pen.shapetransform(
    FRAGMENT_SIZE_MODIFIER * WINDOW_SIZE.x / SCREEN_SIZE.x, 
    0.0, 
    0.0, 
    FRAGMENT_SIZE_MODIFIER * WINDOW_SIZE.y / SCREEN_SIZE.y
)

frame = 0
frame_dilation = 4.0

# p and b are Vec3s
def signed_distance_box(p, b):
    q = p.abs().subtract(b)
    return Vec3.max(q, Vec3(0.0, 0.0, 0.0)).get_length() \
    + min(max(q.r, max(q.g, q.b)), 0.0)

# p is a vector 3, interval is a float
def domain_repetition(p, interval):
    id = p.divide_scalar(interval).add_scalar(0.5).floor()
    r = p.subtract(id.multiply_scalar(interval))
    rand_size = Vec2(1.0, 1.0).add_scalar(math.sin(id.r * 4.2 - id.g * 9.1))
    pillars = signed_distance_box(
        Vec3(r.r, p.g + rand_size.y, r.b),
        Vec3(PILLAR_SIZE.r, PILLAR_SIZE.g, PILLAR_SIZE.b),
    )
    
    return pillars

# p is a vector 3
def map(p):
    pillars = domain_repetition(p.subtract(Vec3(6.0, 1.0, -1.0)), 12.0)
    ground = -1.0 * (p.g - 2.5)
    return min(ground, pillars)

def frag(frag_coord):
    uv = frag_coord.divide(SCREEN_SIZE)
    #uv = Vec2(uv.x * 2.0 - 1.0, uv.y * 2.0 - 1.0)
    uv = uv.multiply_scalar(2.0).subtract_scalar(1.0)
    uv.x = uv.x * (float(SCREEN_SIZE.x) / float(SCREEN_SIZE.y))
    
    ray_origin = Vec3(0.0, 0.0, -3.0)
    ray_direction = Vec3(uv.x, uv.y, 1.0).get_normalized()
    travel = 0.0
    tint = Vec3(0.3, 0.5, 0.3)
    color = Vec3(0.0, 0.0, 1.0)

    for i in range(MARCHES):
        position = ray_origin.add(ray_direction.multiply_scalar(travel))
        
        distance = float(map(position))
        
        travel += distance
                
        if (distance < MIN_RENDER_DISTANCE) or (distance > MAX_RENDER_DISTANCE):
            break

    travel /= 80.0
    
    color = Vec3(travel, travel, travel)
    color = color.multiply(tint)
    color = Vec3.min(Vec3.max(color, Vec3(0.0, 0.0, 0.0)), Vec3(1.0, 1.0, 1.0))
        
    return color

def draw():
    for y_pixel in range(1, int(SCREEN_SIZE.y)):
        for x_pixel in range(1, int(SCREEN_SIZE.x)):
            frag_coord = Vec2(float(x_pixel), float(y_pixel))
            COLOR = frag(frag_coord)
            pen.teleport(frag_coord.x, frag_coord.y)
            pen.color(COLOR.r, COLOR.g, COLOR.b)
            pen.stamp()

while run_simulation:
    pen.clearstamps()
    draw()
    update()
    frame += 1
